# ansible/inventory/hosts.yml
---
all:
  vars:
    ansible_connection: local
    aws_region: eu-west-2
    project_name: mediaserver
    environment: production

localhost:
  hosts:
    127.0.0.1:
      ansible_connection: local
